.\".\" Copyright (c) 2011 Gregor Klinke. All Rights Reserved.
.\" The following commands are required for all man pages.
.Dd January 26, 2011
.Os "Mac OS X"
.Dt HERCHEL 7
.Sh NAME
.Nm herschel
.Nd an general-purpose multiparadigm programming language
.Sh DESCRIPTION
Herschel is a general-purpose multiparadigm programming language.  It is
strongly typed, offering type inference and parametric polymorphism
("generics").  It is thoroughly object oriented (everything is a object),
while its consequent multiple dispatch approach gives it a strong
functional touch.  The object model is class-oriented, supporting multiple
inheritance just as a separation of types ("protocols", "interfaces") and
classes.
.Pp
A (non complete) list of features:
.Bl -dash -compact
.It
object oriented ("everything's an object")
.It
multi dispatch functions
.It
strong functional aproach (while being not strictly functional)
.It
first class functions and "real" closures
.It
fully lexical scoped
.It
automatic memory management (garbage collected)
.It
returnable exceptions
.It
multiple returnvalues
.It
named parameters
.It
modules and namespaces
.It
classes and types ("interfaces")
.It
optional static typing
.It
compiled, though not required by specification
.El
.Sh SEE ALSO
.Xr herschel 1
.Rs
.%A "Gregor Klinke"
.%B "Herschel - Programming language specification"
.Re
.Rs
.%O "http://www.eyestep.org/herschel-spec.pdf"
.Re
.\" .Sh STANDARDS
.\" .Sh HISTORY
.Sh AUTHORS
.An "Gregor Klinke" Aq gck@eyestep.org
.\" .Sh BUGS
